name       : net-snmp
version    : 5.7.3
release    : 1
source     :
    - http://internode.dl.sourceforge.net/project/net-snmp/net-snmp/5.7.3/net-snmp-5.7.3.tar.gz : 12ef89613c7707dc96d13335f153c1921efc9d61d3708ef09f3fc4a7014fb4f0
license    : BSD-3-Clause
summary    : Simple Network Management Protocol
description: |
    Simple Network Management Protocol (SNMP) is a widely used protocol for monitoring the health and welfare of network equipment (eg. routers), computer equipment and even devices like UPSs. Net-SNMP is a suite of applications used to implement SNMP v1, SNMP v2c and SNMP v3 using both IPv4 and IPv6.
builddeps  :
setup      : |
    %configure --with-defaults --disable-static
build      : |
    %make
install    : |
    %make_install
    rm %installroot%/usr/lib/perl5/5.20.1/x86_64-linux/perllocal.pod
