name       : net-snmp
version    : 5.7.3
release    : 3
source     :
    - http://internode.dl.sourceforge.net/project/net-snmp/net-snmp/5.7.3/net-snmp-5.7.3.tar.gz : 12ef89613c7707dc96d13335f153c1921efc9d61d3708ef09f3fc4a7014fb4f0
license    : BSD-3-Clause
summary    : Simple Network Management Protocol
component  : network.util
description: |
    Simple Network Management Protocol (SNMP) is a widely used protocol for monitoring the health and welfare of network equipment (eg. routers), computer equipment and even devices like UPSs. Net-SNMP is a suite of applications used to implement SNMP v1, SNMP v2c and SNMP v3 using both IPv4 and IPv6.
setup      : |
    # Sourced from Fedora to fix perl 5.24 build
    %patch -p1 < $pkgfiles/net-snmp-5.7.3-Fix-Makefile-PL.patch
    %patch -p1 < $pkgfiles/net-snmp-5.7.3-Remove-U64-typedef.patch
    %configure --with-defaults --disable-static
build      : |
    %make
install    : |
    %make_install
    privlib="%perl_privlib%"
    rm -rf "$installdir/$privlib"
