name       : net-snmp
version    : 5.8
release    : 9
source     :
    - http://internode.dl.sourceforge.net/project/net-snmp/net-snmp/5.8/net-snmp-5.8.tar.gz : b2fc3500840ebe532734c4786b0da4ef0a5f67e51ef4c86b3345d697e4976adf
license    : BSD-3-Clause
summary    : Simple Network Management Protocol
component  : network.util
description: |
    Simple Network Management Protocol (SNMP) is a widely used protocol for monitoring the health and welfare of network equipment (eg. routers), computer equipment and even devices like UPSs. Net-SNMP is a suite of applications used to implement SNMP v1, SNMP v2c and SNMP v3 using both IPv4 and IPv6.
setup      : |
    %configure --with-defaults --disable-static
build      : |
    %make
install    : |
    %make_install
    privlib="%perl_privlib%"
    rm -rf "$installdir/$privlib"
